// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/beldeveloper/go-di/controller"
	"github.com/beldeveloper/go-di/repository"
	"github.com/beldeveloper/go-di/service"
)

// Injectors from wire.go:

func InitializeController() controller.Controller {
	user := repository.NewUserMock()
	topic := repository.NewTopicMock()
	vote := service.NewVoteMock(user, topic)
	controllerController := controller.NewMock(vote)
	return controllerController
}
